import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Exo_2 } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const exo2 = Exo_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-exo2",
});

export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={exo2.variable}>
      <body>
        <Header />
        {children}
        <Toaster toastOptions={{ duration: 3000 }} />
        <Footer />
      </body>
    </html>
  );
}
